# Generated by Django 4.1.7 on 2023-03-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_question_name_alter_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portofolio_item',
            old_name='photo',
            new_name='main_photo',
        ),
        migrations.CreateModel(
            name='Photo_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.portofolio_item')),
            ],
        ),
    ]
