# Generated by Django 4.1.7 on 2023-03-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_photo_portofolio_item_main_photo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo_Gallery',
            new_name='Portofolio_Photos',
        ),
    ]
