# Generated by Django 4.1.7 on 2023-03-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_photo_gallery_portofolio_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portofolio_Photos',
            new_name='Portofolio_Photo',
        ),
    ]
