# Generated by Django 4.1.7 on 2023-03-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_portofolio_photos_portofolio_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portofolio_photo',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='portofolio_photo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='base.portofolio_item'),
        ),
    ]
